// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HeartbeatEvent = { observed_at: string, transport_lag_ms?: bigint, queue_depth?: number, liveness?: MailboxLivenessState, };
