// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxAckMode } from "./MailboxAckMode";

export type MailboxAckPolicy = { mode: MailboxAckMode, deadline: string | null, auto_ack_seconds: bigint | null, escalation_ticket: string | null, };
