// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxContentType } from "./MailboxContentType";

export type MailboxBody = { subject: string | null, content: string, content_type: MailboxContentType, };
