// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxSenderRole } from "./MailboxSenderRole";

export type MailboxSender = { id: string, role: MailboxSenderRole, display_name: string | null, contact: string | null, runbook: string | null, };
