// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxDigestAlgorithm } from "./MailboxDigestAlgorithm";

export type MailboxAttachmentDigest = { algorithm: MailboxDigestAlgorithm, value: string, };
