// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxDeliveryState } from "./MailboxDeliveryState";
import type { MailboxMessage } from "./MailboxMessage";

export type MailboxDeliveryEvent = { message: MailboxMessage, state: MailboxDeliveryState, queue_depth: number | null, observed_at: string | null, };
