// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxAudienceScope } from "./MailboxAudienceScope";

export type MailboxAudience = { conversation_id: string | null, worker_id: string | null, scopes: Array<MailboxAudienceScope> | null, allow_broadcast: boolean, };
