// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxAttachmentDigest } from "./MailboxAttachmentDigest";

export type MailboxAttachment = { attachment_id: string, description: string | null, content_type: string, digest: MailboxAttachmentDigest, uri: string | null, };
