// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxAckPolicy } from "./MailboxAckPolicy";
import type { MailboxAttachment } from "./MailboxAttachment";
import type { MailboxAudience } from "./MailboxAudience";
import type { MailboxAuditTrail } from "./MailboxAuditTrail";
import type { MailboxBody } from "./MailboxBody";
import type { MailboxPriority } from "./MailboxPriority";
import type { MailboxRateLimitHint } from "./MailboxRateLimitHint";
import type { MailboxSender } from "./MailboxSender";

/**
 * Canonical mailbox message payload backed by `schemas/mailbox/mailbox-message.yaml`.
 */
export type MailboxMessage = { message_id: string, priority: MailboxPriority, posted_at: string | null, expires_at: string | null, sender: MailboxSender, audience: MailboxAudience | null, body: MailboxBody, ack_policy: MailboxAckPolicy, audit: MailboxAuditTrail, attachments: Array<MailboxAttachment>, tags: { [key in string]?: string }, metadata: Record<string, unknown>, rate_limit: MailboxRateLimitHint | null, };
