// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MailboxAuditTrail = { request_id: string | null, change_ticket: string | null, created_by: string | null, justification: string | null, };
